name: "Publish to npm"
description: "Publishes a package to npm"
inputs:
  package_dir:
    description: "The directory of the package to publish"
    required: true
  tag:
    description: "The npm tag to publish the package under (latest or rc)"
    required: true
runs:
  using: "node12"
  main: "index.js"
