name: Release

on:
  push:
    branches:
      - dev
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Install dependencies
        run: pnpm install

      - name: Generate git diff
        run: |
          PREV_COMMIT=$(git rev-parse HEAD^1)
          git diff $PREV_COMMIT HEAD > changes.diff

      # Use the external Python script to generate release notes
      - name: Generate Release Notes with GPT
        run: |
          python3 scripts/generate_release_notes.py > RELEASE_NOTES.md

      # Commit the generated release notes to the dev branch
      - name: Commit Release Notes
        run: |
          git add RELEASE_NOTES.md
          git commit -m "Generated release notes for dev"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summarize-release-notes:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: generate-release-notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Install dependencies
        run: pnpm install

      # Aggregate all release notes created in dev branch
      - name: Aggregate Release Notes
        run: |
          git log --oneline --grep="Generated release notes for dev" --pretty=format:"%s%n%b" > release_notes_aggregated.txt

      # Use the external Python script to summarize the release notes
      - name: Summarize Release Notes with GPT
        run: |
          python3 scripts/summarize_release_notes.py > SUMMARY_RELEASE_NOTES.md

      # Commit the summarized release notes to the main branch
      - name: Commit Summarized Release Notes
        run: |
          git add SUMMARY_RELEASE_NOTES.md
          git commit -m "Summarized release notes for main"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
