name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Create Changesets version
        run: pnpx changeset version

      - name: Push Changeset version update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version Packages"
          git push

      - name: Create GitHub Release
        uses: changesets/action@v2
        with:
          publish: false
          version: false
          changelog: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Echo statement instead of publishing to npm (for now)
      - name: Echo publish action
        run: echo "This is where the package would be published to npm."
