name: Release

on:
  push:
    branches:
      - dev
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.6.6 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if lasereyes package changed
        id: check_lasereyes_changes
        run: |
          if git diff --name-only HEAD^1 HEAD | grep -q 'packages/lasereyes/'; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Bump version for lasereyes (dev)
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: |
          cd packages/lasereyes
          # Increment the version by a patch and mark it as an RC
          npm version prerelease --preid=rc
          cd ../../
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bumps and changelog for dev
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "RC version bump for lasereyes"
          git pull --rebase origin dev
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version for lasereyes (main)
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          cd packages/lasereyes
          # Increment the version by a patch for main
          npm version patch
          cd ../../
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bumps and changelog for main
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version bump after merge to main for lasereyes"
          git pull --rebase origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Sync main back into dev and bump dev's version again
      - name: Sync main to dev and bump dev version after merge
        if: ${{ github.ref == 'refs/heads/main' && env.changed == 'true' }}
        run: |
          git checkout dev
          git pull origin dev
          git merge origin/main
          cd packages/lasereyes
          # Bump the dev version as a pre-release
          npm version prerelease --preid=rc
          cd ../../
          git add .
          git commit -m "Bump dev version after main sync"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Setup pnpm
        run: echo "Workflow completed!"
