name: Release

on:
  push:
    branches:
      - dev
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.6.6 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if lasereyes package changed
        id: check_lasereyes_changes
        run: |
          if pnpm changeset status | grep -q lasereyes; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Add Changeset if lasereyes package changed
        if: ${{ env.changed == 'true' }}
        run: |
          pnpm changeset add --empty --force --message "chore: auto-bump lasereyes version (patch)"

      - name: Run Changesets version bump for dev
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: pnpm changeset version

      - name: Commit version bumps and changelog for dev
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "RC version bump for lasereyes"
          git pull --rebase origin dev
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Changesets version bump for main
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/main' }}
        run: pnpm changeset version

      - name: Commit version bumps and changelog for main
        if: ${{ env.changed == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version bump after merge to main for lasereyes"
          git pull --rebase origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Setup pnpm
        run: echo "Workflow completed!"
