name: Release

on:
  push:
    branches:
      - dev
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.6.6 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if lasereyes packages changed
        id: check_lasereyes_changes
        run: |
          if git diff --name-only HEAD^1 HEAD | grep -q 'packages/lasereyes/'; then
            echo "lasereyes_changed=true" >> $GITHUB_ENV
          else
            echo "lasereyes_changed=false" >> $GITHUB_ENV
          fi
          if git diff --name-only HEAD^1 HEAD | grep -q 'packages/lasereyes-core/'; then
            echo "lasereyes_core_changed=true" >> $GITHUB_ENV
          else
            echo "lasereyes_core_changed=false" >> $GITHUB_ENV
          fi
          if git diff --name-only HEAD^1 HEAD | grep -q 'packages/lasereyes-react/'; then
            echo "lasereyes_react_changed=true" >> $GITHUB_ENV
          else
            echo "lasereyes_react_changed=false" >> $GITHUB_ENV
          fi

      # Install action dependencies for bump-version-and-commit
      - name: Install action dependencies (bump-version-and-commit)
        run: |
          cd .github/actions/bump-version-and-commit
          npm install

      # Install action dependencies for publish-to-npm
      - name: Install action dependencies (publish-to-npm)
        run: |
          cd .github/actions/publish-to-npm
          npm install

      # Bump version for lasereyes-core (dev)
      - name: Bump version for lasereyes-core (dev)
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/dev' }}
        uses: ./.github/actions/bump-version-and-commit
        with:
          package_dir: "packages/lasereyes-core"
          preid: "rc"

      # Commit version bump for lasereyes-core (dev)
      - name: Commit version bump for lasereyes-core (dev)
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/lasereyes-core/package.json
          git commit -m "RC version bump for lasereyes-core"
          git push origin dev

      # Publish lasereyes-core (RC) to npm
      - name: Publish lasereyes-core (RC)
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/dev' }}
        uses: ./.github/actions/publish-to-npm
        with:
          package_dir: "packages/lasereyes-core"
          npm_tag: "rc"

      # Bump version for lasereyes-react (dev)
      - name: Bump version for lasereyes-react (dev)
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/dev' }}
        uses: ./.github/actions/bump-version-and-commit
        with:
          package_dir: "packages/lasereyes-react"
          preid: "rc"

      # Commit version bump for lasereyes-react (dev)
      - name: Commit version bump for lasereyes-react (dev)
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/lasereyes-react/package.json
          git commit -m "RC version bump for lasereyes-react"
          git push origin dev

      # Publish lasereyes-react (RC) to npm
      - name: Publish lasereyes-react (RC)
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/dev' }}
        uses: ./.github/actions/publish-to-npm
        with:
          package_dir: "packages/lasereyes-react"
          npm_tag: "rc"

      # Bump version for lasereyes-core (main)
      - name: Bump version for lasereyes-core (main)
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/bump-version-and-commit
        with:
          package_dir: "packages/lasereyes-core"

      # Commit version bump for lasereyes-core (main)
      - name: Commit version bump for lasereyes-core (main)
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/lasereyes-core/package.json
          git commit -m "Version bump for lasereyes-core after merge to main"
          git push origin main

      # Publish lasereyes-core to npm
      - name: Publish lasereyes-core
        if: ${{ env.lasereyes_core_changed == 'true' && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/publish-to-npm
        with:
          package_dir: "packages/lasereyes-core"
          npm_tag: "latest"

      # Bump version for lasereyes-react (main)
      - name: Bump version for lasereyes-react (main)
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/bump-version-and-commit
        with:
          package_dir: "packages/lasereyes-react"

      # Commit version bump for lasereyes-react (main)
      - name: Commit version bump for lasereyes-react (main)
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/lasereyes-react/package.json
          git commit -m "Version bump for lasereyes-react after merge to main"
          git push origin main

      # Publish lasereyes-react to npm
      - name: Publish lasereyes-react
        if: ${{ env.lasereyes_react_changed == 'true' && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/publish-to-npm
        with:
          package_dir: "packages/lasereyes-react"
          npm_tag: "latest"

      # Sync main to dev and bump dev version after merge
      - name: Sync main to dev and bump dev version after merge
        if: ${{ github.ref == 'refs/heads/main' && (env.lasereyes_changed == 'true' || env.lasereyes_core_changed == 'true' || env.lasereyes_react_changed == 'true') }}
        run: |
          git checkout dev
          git pull origin dev
          git merge -X theirs origin/main
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
